package cliente.vistas.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JTable;

import cliente.controladores.OfADController;
import cliente.vistas.VistaOfAD;

public class OfAD extends javax.swing.JFrame {
	private VistaOfAD vistaPadre;

	/** Creates new form test */
	public OfAD(VistaOfAD vista) {
		initComponents();
		vistaPadre = vista;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		this.setTitle("Oferta de Artículos disponibles (OfAD)");

		jScrollPane1 = new javax.swing.JScrollPane();
		tablaArtDisponibles = new JTable();
		jScrollPane2 = new javax.swing.JScrollPane();
		tablaArtNuevos = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		btn_salir = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();

		setTitle("Oferta de Artículos Disponibles");

		tablaArtDisponibles.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {}, new String[] { "Artículo", "Descripción",
						"Precio", "Oferta" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false, false, false };

			@Override
			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			@Override
			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tablaArtDisponibles);
		tablaArtDisponibles.getColumnModel().getColumn(0).setMinWidth(100);
		tablaArtDisponibles.getColumnModel().getColumn(0)
				.setPreferredWidth(100);
		tablaArtDisponibles.getColumnModel().getColumn(0).setMaxWidth(100);
		tablaArtDisponibles.getColumnModel().getColumn(2).setMinWidth(70);
		tablaArtDisponibles.getColumnModel().getColumn(2).setPreferredWidth(70);
		tablaArtDisponibles.getColumnModel().getColumn(2).setMaxWidth(70);
		tablaArtDisponibles.getColumnModel().getColumn(3).setMinWidth(70);
		tablaArtDisponibles.getColumnModel().getColumn(3).setPreferredWidth(70);
		tablaArtDisponibles.getColumnModel().getColumn(3).setMaxWidth(70);

		tablaArtNuevos.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {}, new String[] { "Artículo", "Descripción",
						"Precio", "Oferta" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false, false, false };

			@Override
			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			@Override
			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane2.setViewportView(tablaArtNuevos);
		tablaArtNuevos.getColumnModel().getColumn(0).setMinWidth(100);
		tablaArtNuevos.getColumnModel().getColumn(0).setPreferredWidth(100);
		tablaArtNuevos.getColumnModel().getColumn(0).setMaxWidth(100);
		tablaArtNuevos.getColumnModel().getColumn(2).setMinWidth(70);
		tablaArtNuevos.getColumnModel().getColumn(2).setPreferredWidth(70);
		tablaArtNuevos.getColumnModel().getColumn(2).setMaxWidth(70);
		tablaArtNuevos.getColumnModel().getColumn(3).setMinWidth(70);
		tablaArtNuevos.getColumnModel().getColumn(3).setPreferredWidth(70);
		tablaArtNuevos.getColumnModel().getColumn(3).setMaxWidth(70);

		jLabel1.setText("Artículos Disponibles");

		jLabel2.setText("Artículos Nuevos");

		jLabel3.setText("Oferta de Artículos Disponibles (OfAD)");

		btn_salir.setText("Salir");

		btn_salir.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				((OfADController)vistaPadre.getControlador()).cerrar();
			}
		});

		jLabel4.setText("Última Actualización:");

		jTextField1.setEditable(false);
		jTextField1.setText("DD/MM/AAAA");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel2)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel4)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jTextField1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												90,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGap(
																				236,
																				236,
																				236)
																		.addComponent(
																				jLabel3))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jScrollPane2,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								683,
																								Short.MAX_VALUE))))
										.addContainerGap())
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap()

										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)

										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												268, Short.MAX_VALUE)
										.addComponent(btn_salir).addGap(33, 33,
												33)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel3)
										.addGap(13, 13, 13)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												155,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												157,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(btn_salir))
										.addContainerGap(16, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btn_salir;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable tablaArtNuevos;
	private javax.swing.JTable tablaArtDisponibles;
	private javax.swing.JTextField jTextField1;

	// End of variables declaration//GEN-END:variables

	public javax.swing.JTable getTablaArtDisponibles() {
		return tablaArtDisponibles;
	}

	public javax.swing.JTable getTablaArtNuevos() {
		return tablaArtNuevos;
	}

}
