/*
 * VentaArticulos.java
 *
 * Created on 6 de abril de 2009, 00:44
 */

package cliente.vistas.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.util.Calendar;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

import server.VO.clientes.ClienteVO;

import cliente.constantes.ZaraConstants;
import cliente.controladores.VentaArticulosController;
import cliente.modelo.DatosT;
import cliente.principal.ZaraMain;
import cliente.vistas.VistaVentaArticulos;
import cliente.vistas.gui.tables.VentasCantidadTableRenderer;
import cliente.vistas.gui.tables.VentasTableButtonEditor;
import cliente.vistas.gui.tables.VentasTableButtonRenderer;

/**
 *
 * @author  chama
 */
public class VentaArticulos extends JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VistaVentaArticulos vistaPadre;
    
	/** Creates new form VentaArticulos */
    public VentaArticulos(VistaVentaArticulos vista) {
        initComponents();
        vistaPadre = vista;
    }

    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	this.setTitle("Venta de Artículos");
    	
        jPanel1 = new JPanel();
        txt_referencia = new JTextField();

        txtDetalles = new JEditorPane();
        txtDetalles.setAutoscrolls(false);
        txtDetalles.setEditable(false);
        txtDetalles.setContentType("text/html"); 
        
        lblDetalles = new JLabel();
        jLabel1 = new JLabel();
        btn_agregar = new JButton();
        jScrollPane1 = new JScrollPane();
        tablaArticulos = new JTable();
        jPanel2 = new JPanel();
        jLabel2 = new JLabel();
        comboFactura = new JComboBox();
        jLabel4 = new JLabel();
        cuitcuilL = new JLabel("cuit/cuil:");
        razonsocialL = new JLabel("Razon Social:");
        direccionL = new JLabel("Dirección:");
        nomCliente = new JTextField();
        cuitcuil = new JTextField();
        razonsocial = new JTextField();
        direccion = new JTextField();
        lblFecha = new JLabel();
        subtotal = new JLabel();
        iva = new JLabel();
        total = new JLabel();
        btn_generarFactura = new JButton();
        btn_salir = new JButton();
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
       
        lblDetalles.setText("Detalles: ");

        jPanel1.setBorder(BorderFactory.createTitledBorder("Artículos"));

        jLabel1.setText("ID:");
                        
        JScrollPane scrollingArea = new JScrollPane(txtDetalles);
        scrollingArea.setAutoscrolls(false);

        
        txt_referencia.addKeyListener(new KeyListener(){

			public void keyPressed(KeyEvent e) {			
				if (e.getKeyCode() == KeyEvent.VK_ENTER )
				{
					doAgregarArticulo();
				}
			}
			public void keyReleased(KeyEvent arg0) {}
			public void keyTyped(KeyEvent arg0) {}
		});
        
        cuitcuil.addFocusListener(new FocusListener(){

			public void focusGained(FocusEvent e) {							
			}

			public void focusLost(FocusEvent e) {
				doBuscarCliente();
			}});
        
        cuitcuil.addKeyListener(new KeyListener(){

			public void keyPressed(KeyEvent e) {			
				if ((e.getKeyCode() == KeyEvent.VK_ENTER ))
				{
					doBuscarCliente();
				}
			}
			public void keyReleased(KeyEvent arg0) {}
			public void keyTyped(KeyEvent arg0) {}
		});

        btn_agregar.setText("Agregar");
        
        btn_agregar.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
				doAgregarArticulo();
			}
        	
        });
        
       tablaArticulos.setModel(new DefaultTableModel() {
		private static final long serialVersionUID = 1L;
			Class[] types = new Class [] {
                Object.class, Object.class, Object.class, Object.class, Boolean.class, Integer.class, JButton.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true 
            };

            @Override
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
                        
            @Override
			public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        ((DefaultTableModel)tablaArticulos.getModel()).setDataVector(
        		new Object[][]{},
        		new Object[]{"Referencia", "Línea", "Descripción", "Precio", "Precio Oferta?", "Cantidad", "Borrar"}
        );
        
        tablaArticulos.setEditingColumn(1);
        jScrollPane1.setViewportView(tablaArticulos);
        
        tablaArticulos.setDefaultRenderer(Integer.class, new VentasCantidadTableRenderer());                
        tablaArticulos.setDefaultRenderer(JButton.class, new VentasTableButtonRenderer());
        tablaArticulos.setDefaultEditor(JButton.class, new VentasTableButtonEditor(new JCheckBox()));
        
        ((VentasTableButtonEditor)tablaArticulos.getDefaultEditor(JButton.class)).addCellEditorListener(new CellEditorListener(){

			public void editingCanceled(ChangeEvent e) {}

			public void editingStopped(ChangeEvent e) {
				long ref = (Long)tablaArticulos.getModel().getValueAt(tablaArticulos.getSelectedRow(), 0);
				
				((VentaArticulosController)vistaPadre.getControlador()).borrarArticulo(ref, tablaArticulos.getSelectedRow());
			}});
        
        tablaArticulos.getDefaultEditor(Boolean.class).addCellEditorListener(new CellEditorListener(){

			public void editingCanceled(ChangeEvent e) {}

			public void editingStopped(ChangeEvent e) {
				
				long ref = (Long)tablaArticulos.getModel().getValueAt(tablaArticulos.getSelectedRow(), 0);
				
				if ((Boolean)tablaArticulos.getModel().getValueAt(tablaArticulos.getSelectedRow(), tablaArticulos.getSelectedColumn())){
					((VentaArticulosController)vistaPadre.getControlador()).togglePrecio(ref, ZaraConstants.PRECIO_OFERTA, tablaArticulos.getSelectedRow());
				}
				else
				{
					((VentaArticulosController)vistaPadre.getControlador()).togglePrecio(ref, ZaraConstants.PRECIO_LISTA, tablaArticulos.getSelectedRow());
				}
			}});
                
                

        
        tablaArticulos.getColumnModel().getColumn(0).setMinWidth(100);
        tablaArticulos.getColumnModel().getColumn(0).setPreferredWidth(100);
        tablaArticulos.getColumnModel().getColumn(0).setMaxWidth(100);
        tablaArticulos.getColumnModel().getColumn(1).setMinWidth(70);
        tablaArticulos.getColumnModel().getColumn(1).setPreferredWidth(70);
        tablaArticulos.getColumnModel().getColumn(1).setMaxWidth(70);
        tablaArticulos.getColumnModel().getColumn(3).setMinWidth(70);
        tablaArticulos.getColumnModel().getColumn(3).setPreferredWidth(70);
        tablaArticulos.getColumnModel().getColumn(3).setMaxWidth(70);
        tablaArticulos.getColumnModel().getColumn(4).setMinWidth(70);
        tablaArticulos.getColumnModel().getColumn(4).setPreferredWidth(70);
        tablaArticulos.getColumnModel().getColumn(4).setMaxWidth(70);
        tablaArticulos.getColumnModel().getColumn(5).setMinWidth(70);
        tablaArticulos.getColumnModel().getColumn(5).setPreferredWidth(70);
        tablaArticulos.getColumnModel().getColumn(5).setMaxWidth(70);
        tablaArticulos.getColumnModel().getColumn(6).setMinWidth(50);
        tablaArticulos.getColumnModel().getColumn(6).setPreferredWidth(50);
        tablaArticulos.getColumnModel().getColumn(6).setMaxWidth(50);


        tablaArticulos.getModel().addTableModelListener(new TableModelListener(){

			public void tableChanged(TableModelEvent arg0) {
				setVals();
				
			}
        	
        	
        });

        

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(txt_referencia, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)                                              
                .addComponent(btn_agregar)
                .addGap(6, 6, 6)                                           
            	.addContainerGap(20, Short.MAX_VALUE)
            	.addComponent(lblDetalles)
            	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            	.addComponent(scrollingArea, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
            	.addContainerGap())
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 847, GroupLayout.PREFERRED_SIZE)
                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                //.addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)                    
                    .addComponent(txt_referencia, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)                                                           
                    .addComponent(btn_agregar, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lblDetalles)
                    .addComponent(scrollingArea, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)                  
                    .addGap(18, 18, 18))
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE)));

        jPanel1Layout.linkSize(SwingConstants.VERTICAL, new java.awt.Component[] {btn_agregar, jLabel1, txt_referencia, nomCliente});

        jPanel2.setBorder(BorderFactory.createTitledBorder("Datos de Factura"));

        jLabel2.setText("Tipo de Factura:");

        comboFactura.setModel(new DefaultComboBoxModel(new String[] { "A", "B", "C" }));

        comboFactura.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent arg0) {
				setVals();				
			}
        	
        	
        });
        
        
        jLabel4.setText("Cliente:");

        nomCliente.setText("");
        cuitcuil.setText("");
        razonsocial.setText("");
        direccion.setText("");

        lblFecha.setText("Fecha: " + DateFormat.getInstance().format((Calendar.getInstance().getTime())));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);

        
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(cuitcuilL)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cuitcuil, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
                    .addGap(138, 138, 138)
                    .addComponent(jLabel2)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(comboFactura, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                    .addComponent(lblFecha)
                    .addGap(21, 21, 21))
                 .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel4)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nomCliente, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                    .addGap(138, 138, 138)
                    .addComponent(razonsocialL)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(razonsocial, GroupLayout.PREFERRED_SIZE, 180, GroupLayout.PREFERRED_SIZE))                    
                 .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(direccionL)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(direccion, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE)
                    .addGap(138, 138, 138))              
            );
        
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboFactura, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha)
                    .addComponent(cuitcuilL)
                    .addComponent(cuitcuil))
                .addGap(6,6,6)    
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                	.addComponent(jLabel4)
                    .addComponent(nomCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                	.addComponent(razonsocial)
                	.addComponent(razonsocialL))                
                .addGap(6,6,6)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    	.addComponent(direccion)
                    	.addComponent(direccionL)
                   )                    
                 );
        
        
        
        
        
        sub =0;
        subtotal.setText("Subtotal: " + sub);

        imp=0;
        iva.setText("IVA: " + imp);

        tot=0;
        total.setText("TOTAL: "+ tot);

        btn_generarFactura.setText("Generar Factura");
        btn_generarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doGenerarFactura(evt);
                
            }
        });

        btn_salir.setText("Salir");
        
        btn_salir.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent arg0) {
				doSalir();
			}});

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(subtotal)
                                .addComponent(iva)
                                .addComponent(total))
                            .addGap(36, 36, 36))
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap()))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_generarFactura)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_salir)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtotal)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iva)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salir)
                    .addComponent(btn_generarFactura))
                .addContainerGap(18, Short.MAX_VALUE))
        );

            
               
        pack();
    }
	   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btn_agregar;
    private JButton btn_generarFactura;
    private JButton btn_salir;
    private JComboBox comboFactura;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel subtotal;
    private JLabel jLabel4;
    private JLabel lblFecha;
    private JLabel iva;
    private JLabel total;
    private JLabel lblDetalles;
    private JLabel cuitcuilL;
    private JLabel razonsocialL;
    private JLabel direccionL;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JTable tablaArticulos;
    private JTextField txt_referencia;
    private JTextField nomCliente;
    private JTextField cuitcuil;
    private JTextField razonsocial;
    private JTextField direccion;
    private JEditorPane txtDetalles;
    private float sub;
    private float imp;
    private float tot;

	public JTable getTablaArticulos() {
		return tablaArticulos;
	}
	
	private void doSalir(){
		((VentaArticulosController)vistaPadre.getControlador()).cerrar();
	}
	
	private void doAgregarArticulo(){
		try {
			long ref = Long.parseLong(txt_referencia.getText());			
			((VentaArticulosController)vistaPadre.getControlador()).agregarArticulo(ref);
		}		
		catch (NumberFormatException e){
			((VentaArticulosController)vistaPadre.getControlador()).showNumericoPopup();			
		}
	}
	
	private void doGenerarFactura(ActionEvent evt) {
		
		ClienteVO cliente = new ClienteVO();
		cliente.setCuit(this.cuitcuil.getText());
		cliente.setNombre(this.nomCliente.getText());
		cliente.setRazonSocial(this.razonsocial.getText());
		cliente.setDireccion(this.direccion.getText());
		
		DatosT datosT = new DatosT(this.sub, this.imp, this.tot);
					
	    DefaultTableModel model = (DefaultTableModel) tablaArticulos.getModel();
	    ((VentaArticulosController)vistaPadre.getControlador()).nuevaVenta(model.getDataVector(), datosT, cliente);
	    
	      
	}
	
	private void doBuscarCliente(){
		
		if (this.cuitcuil.getText().isEmpty()){
			this.cuitcuil.setText("0");
		}
		
		ClienteVO cliente = new ClienteVO();
		cliente = ((VentaArticulosController) vistaPadre.getControlador()).getCliente(cuitcuil.getText());
		
		if (cliente != null){
			this.nomCliente.setText(cliente.getNombre());
			this.razonsocial.setText(cliente.getRazonSocial());
			this.direccion.setText(cliente.getDireccion());
		}
		
		
	}

	public JEditorPane getTxtDetalles() {
		return txtDetalles;
	}
	
	public String getTipoFactura(){
		return this.comboFactura.getSelectedItem().toString();
	}
	
	public void setIVA(){
		
		DecimalFormat dec = new DecimalFormat("$#0.00");
		
		if (this.comboFactura.getSelectedItem().toString().equalsIgnoreCase("A")){
			sub = (float) (sub/1.21);
			imp = (float) (sub*0.21);
			subtotal.setText("Subtotal: " + dec.format(sub));
			iva.setText("IVA: " + dec.format(imp));
			enableFields();
	    };
		
		if (this.comboFactura.getSelectedItem().toString().equalsIgnoreCase("B")){
			imp=0;
	        iva.setText("IVA: " + dec.format(imp));
	        disableFields();
		};

		if (this.comboFactura.getSelectedItem().toString().equalsIgnoreCase("C")){
			imp=0;
	        iva.setText("IVA: " + dec.format(imp));
	        disableFields();
		};
	}
	
	public void setSubtotal(){
		DecimalFormat dec = new DecimalFormat("$#0.00");
		sub = 0;
		
		for (int i=0;i<tablaArticulos.getRowCount();i++){
			sub = sub + (new Float(tablaArticulos.getModel().getValueAt(i, 3).toString())* new Float(tablaArticulos.getModel().getValueAt(i, 5).toString()));
		}
		
		subtotal.setText("Subtotal: " + dec.format(sub));

	}
	
	public void setTotal(){
		DecimalFormat dec = new DecimalFormat("$#0.00");
		
		tot=sub+imp;
        total.setText("TOTAL: "+ dec.format(tot));
	}
	
	public void setVals(){
		setSubtotal();
		setIVA();
		setTotal();
	}

	public void disableFields(){
		cuitcuil.setText("0");
		cuitcuil.setEditable(false);
		nomCliente.setEditable(false);
		razonsocial.setEditable(false);
		direccion.setEditable(false);
		doBuscarCliente();
	}
	public void enableFields(){
		cuitcuil.setEditable(true);
		nomCliente.setEditable(true);
		razonsocial.setEditable(true);
		direccion.setEditable(true);
	}
	
	
    // End of variables declaration//GEN-END:variables

}
