
package cliente.vistas.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.WindowConstants;

import cliente.controladores.ListadoPalcController;
import cliente.vistas.VistaListadoPALC;

public class ListadoPALC extends javax.swing.JFrame {
    private VistaListadoPALC vistaPadre;
    
	public javax.swing.JTable getTablaArt() {
		return tablaArt;
	}

	/** Creates new form ListadoPALC */
    public ListadoPALC(VistaListadoPALC vista) {
        initComponents();
        vistaPadre = vista;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	this.setTitle("Generar 'Pedido de Artículos a La Coruña' (PALC)");
    	
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArt = new javax.swing.JTable();
        btn_salir = new javax.swing.JButton();
        
        setTitle("Listado de Pedidos a La Coruña");
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        	
        jLabel1.setText("Listado Completo de Artículos a Pedir");
        
        btn_salir.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
				doSalir();
			}});

        tablaArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Artículo", "Descripción", "Cant. Pedida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            @Override
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
			public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaArt);
        tablaArt.getColumnModel().getColumn(0).setMinWidth(100);
        tablaArt.getColumnModel().getColumn(0).setPreferredWidth(100);
        tablaArt.getColumnModel().getColumn(0).setMaxWidth(100);
        tablaArt.getColumnModel().getColumn(2).setMinWidth(100);
        tablaArt.getColumnModel().getColumn(2).setPreferredWidth(100);
        tablaArt.getColumnModel().getColumn(2).setMaxWidth(100);

        btn_salir.setText("Salir");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                        .addComponent(btn_salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_salir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        ))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void doSalir() {
    	((ListadoPalcController)vistaPadre.getControlador()).cerrar();
	}


	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaArt;
    // End of variables declaration//GEN-END:variables

}
