
package cliente.vistas.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.WindowConstants;

import cliente.controladores.PalcController;
import cliente.vistas.VistaPALC;

public class PALC extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	private VistaPALC vistaPadre;
    
	/** Creates new form PALC */
    public PALC(VistaPALC vista) {
        initComponents();
        vistaPadre = vista;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	this.setTitle("Generar 'Pedido de Artículos a La Coruña' (PALC)");
    	
        jLabel1 = new javax.swing.JLabel();                
        btn_generar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        articulos = new javax.swing.JTable();
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        setTitle("Pedidos de Articulos a La Coruña");
        
        jLabel1.setText("Pedido de Artículos a La Coruña (PALC)");
        

        btn_generar.setText("Generar PALC");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doGeneraPALC();
            }            
        });

        btn_salir.setText("Salir");
        
        btn_salir.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
				doSalir();				
			}});


        jLabel7.setText("Artículos a Incluir");

        jLabel8.setText("Ingrese ID del Artículo:");
        

        btn_agregar.setText("Agregar");
        
        btn_agregar.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
				doAgregarArticulo(txtArticulo.getText());				
			}});

        articulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Artículo", "Descripción", "Ventas", "Pend d/Envío", "Stock", "PdP", "Pedir", "Cant."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            @Override
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
			public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(articulos);
        articulos.getColumnModel().getColumn(0).setMinWidth(100);
        articulos.getColumnModel().getColumn(0).setPreferredWidth(100);
        articulos.getColumnModel().getColumn(0).setMaxWidth(100);
        articulos.getColumnModel().getColumn(2).setMinWidth(70);
        articulos.getColumnModel().getColumn(2).setPreferredWidth(70);
        articulos.getColumnModel().getColumn(2).setMaxWidth(70);
        articulos.getColumnModel().getColumn(3).setMinWidth(70);
        articulos.getColumnModel().getColumn(3).setPreferredWidth(70);
        articulos.getColumnModel().getColumn(3).setMaxWidth(70);
        articulos.getColumnModel().getColumn(4).setMinWidth(70);
        articulos.getColumnModel().getColumn(4).setPreferredWidth(70);
        articulos.getColumnModel().getColumn(4).setMaxWidth(70);
        articulos.getColumnModel().getColumn(5).setMinWidth(70);
        articulos.getColumnModel().getColumn(5).setPreferredWidth(70);
        articulos.getColumnModel().getColumn(5).setMaxWidth(70);
        articulos.getColumnModel().getColumn(6).setMinWidth(70);
        articulos.getColumnModel().getColumn(6).setPreferredWidth(70);
        articulos.getColumnModel().getColumn(6).setMaxWidth(70);
        articulos.getColumnModel().getColumn(7).setMinWidth(70);
        articulos.getColumnModel().getColumn(7).setPreferredWidth(70);
        articulos.getColumnModel().getColumn(7).setMaxWidth(70);


        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_agregar)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_agregar))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Articulos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1))                    
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                        .addComponent(btn_generar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salir)))
                .addGap(20, 20, 20)))));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)                
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_salir)
                            .addComponent(btn_generar))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            )
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void doAgregarArticulo(String referencia) {
    	try {
		((PalcController)vistaPadre.getControlador()).agregaArticulo(new Long(referencia));
    	}    	
    	catch (NumberFormatException e) {
    		((PalcController)vistaPadre.getControlador()).showNumericoPopup();
    	}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JLabel jLabel1;    
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable articulos;    
    private javax.swing.JTextField txtArticulo;
    // End of variables declaration//GEN-END:variables
    
    private void doGeneraPALC() {
    	((PalcController)vistaPadre.getControlador()).registraPALC();
    }
    
    private void doSalir() {
    	((PalcController)vistaPadre.getControlador()).cerrar();
    }

	public javax.swing.JTable getArticulos() {
		return articulos;
	}

	public void setArticulos(javax.swing.JTable articulos) {
		this.articulos = articulos;
	}
    
    

}
