
package cliente.vistas.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import cliente.controladores.EnvTController;
import cliente.vistas.VistaRecEnvT;

public class RecEnvT extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	private VistaRecEnvT vistaPadre;
    
	/** Creates new form RecEnvT */
    public RecEnvT(VistaRecEnvT vista) {
        initComponents();
        vistaPadre = vista;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	this.setTitle("Recibir 'Envío a tienda' (EnvT)");
    
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        txt_hora = new JTextField();
        jLabel3 = new JLabel();
        jScrollPane1 = new JScrollPane();
        tablaArtRecibidos = new JTable();
        jLabel4 = new JLabel();
        jScrollPane2 = new JScrollPane();
        tablaArtPendientes = new JTable();
        btn_salir = new JButton();
        btn_registrarEnvT = new JButton();
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        setTitle("Recepción de Envíos a Tienda");
        
        jLabel1.setText("Recepción de Envios a Tienda (EnvT)");

        jLabel2.setText("Hora de Arribo:");

        txt_hora.setEditable(false);
        txt_hora.setText("HH:MM:SS - DD/MM/AAAA");

        jLabel3.setText("Artículos Recibidos");

        tablaArtRecibidos.setModel(new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Artículo", "Descripción", "Cant. Recibida", "Stock Total"
            }
        ) {

			private static final long serialVersionUID = 1L;
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @Override
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
			public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaArtRecibidos);
        tablaArtRecibidos.getColumnModel().getColumn(0).setMinWidth(100);
        tablaArtRecibidos.getColumnModel().getColumn(0).setPreferredWidth(100);
        tablaArtRecibidos.getColumnModel().getColumn(0).setMaxWidth(100);
        tablaArtRecibidos.getColumnModel().getColumn(2).setMinWidth(100);
        tablaArtRecibidos.getColumnModel().getColumn(2).setPreferredWidth(100);
        tablaArtRecibidos.getColumnModel().getColumn(2).setMaxWidth(100);
        tablaArtRecibidos.getColumnModel().getColumn(3).setMinWidth(100);
        tablaArtRecibidos.getColumnModel().getColumn(3).setPreferredWidth(100);
        tablaArtRecibidos.getColumnModel().getColumn(3).setMaxWidth(100);

        jLabel4.setText("Artículos Pendientes");

        tablaArtPendientes.setModel(new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Artículo", "Descripción", "Cant. Recibida", "Cant. Pendiente", "Stock Actual"
            }
        ) {
			private static final long serialVersionUID = 1L;
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            @Override
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
			public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaArtPendientes);
        tablaArtPendientes.getColumnModel().getColumn(0).setMinWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(0).setPreferredWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(0).setMaxWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(2).setMinWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(2).setPreferredWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(2).setMaxWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(3).setMinWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(3).setPreferredWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(3).setMaxWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(4).setMinWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(4).setPreferredWidth(100);
        tablaArtPendientes.getColumnModel().getColumn(4).setMaxWidth(100);


        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	((EnvTController)vistaPadre.getControlador()).cerrar();
            }
        });

        btn_registrarEnvT.setText("Registrar EnvT");
        
        btn_registrarEnvT.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				((EnvTController)vistaPadre.getControlador()).cargarEnvT(true);				
			}        	
        });


        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_hora, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(btn_registrarEnvT)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_hora, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_salir)
                        .addComponent(btn_registrarEnvT))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        ))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btn_salir;
    private JButton btn_registrarEnvT;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JTable tablaArtRecibidos;
    private JTable tablaArtPendientes;
    private JTextField txt_hora;
    // End of variables declaration//GEN-END:variables

	public JTable getTablaArtRecibidos() {
		return this.tablaArtRecibidos;
	}

	public JTable getTablaArtPendientes() {
		return this.tablaArtPendientes;
	}

	public JTextField getTxt_hora() {
		return txt_hora;
	}

}
